[package]
name = "ollama-model-report"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
glob = "0.3"
dirs = "5.0"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
